---

- name: "Create Agent target directory"
  file:
    path: "/home/{{ user }}/myAgent"
    state: "directory"
    mode: "0755"

- name: "Download the Linux Agent"
  get_url:
    url: "https://vstsagentpackage.azureedge.net/agent/2.160.0/vsts-agent-linux-x64-2.160.0.tar.gz"
    dest: "/home/{{ user }}/myAgent/vsts-agent-linux-x64-2.160.0.tar.gz"
    mode: "0755"

- name: "Unarchive the TAR GunZip Agent file"
  unarchive:
    remote_src: yes
    src: "/home/{{ user }}/myAgent/vsts-agent-linux-x64-2.160.0.tar.gz"
    dest: "/home/{{ user }}/myAgent"

- name: "Run the Agent's shell configuration script"
  command: "{{ agentDir }}/config.sh --unattended --url {{ orgUrl }} --auth pat --token {{ azToken }} --pool Default --agent myAgent --acceptTeeEula"

- name: "Configure the Agent to run as a SystemD Service"
  command: "sudo ./svc.sh install"
  args:
    chdir: "{{ agentDir }}"
  
- name: "Start the Agent SystemD Service"
  command: "sudo ./svc.sh start"
  args:
    chdir: "{{ agentDir }}"

- name: "Verify the status of the Agent"
  command: "sudo ./svc.sh status"
  args:
    chdir: "{{ agentDir }}"

#- name: "Force TAR extraction on the Agent file"
#  command: "tar -zxvf /home/{{ user }}/myAgent/vsts-agent-linux-x64-2.160.0.tar.gz /home/{{ user }}/myAgent"
#  become: yes

...
