---

- name: "Create Agent target directory"
  file:
    path: "/home/{{ user }}/myAgent"
    state: "directory"
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: "Download the Linux Agent"
  get_url:
    url: "https://vstsagentpackage.azureedge.net/agent/2.160.0/vsts-agent-linux-x64-2.160.0.tar.gz"
    dest: "/home/{{ user }}/myAgent/vsts-agent-linux-x64-2.160.0.tar.gz"
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: "Unarchive the TAR GunZip Agent file"
  unarchive:
    remote_src: yes
    src: "/home/{{ user }}/myAgent/vsts-agent-linux-x64-2.160.0.tar.gz"
    dest: "/home/{{ user }}/myAgent"
    owner: "{{ user }}"
    group: "{{ user }}"
    
- name: "Fix permissions - Unarchive does not allow recurse for filez that are decompressed."
  file:
    path: "/home/{{ user }}/myAgent"
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes

- name: "Run the Agent's shell configuration script"
  command: "{{ agentDir }}/config.sh --unattended --url {{ orgUrl }} --auth pat --token {{ azToken }} --pool Default --agent {{ lookup('env','AGENTNAME') }} --acceptTeeEula"
  become: yes
  become_method: "su"
  become_user: "{{ user }}"
  become_flags: '-s /bin/sh'

- name: "Configure the Agent to run as a SystemD Service"
  command: "sudo ./svc.sh install"
  become: yes
  become_method: "su"
  become_user: "{{ user }}"
  become_flags: '-s /bin/sh'
  args:
    chdir: "{{ agentDir }}"
  
- name: "Start the Agent SystemD Service"
  command: "sudo ./svc.sh start"
  become: yes
  become_method: "su"
  become_user: "{{ user }}"
  become_flags: '-s /bin/sh'
  args:
    chdir: "{{ agentDir }}"

- name: "Verify the status of the Agent"
  command: "sudo ./svc.sh status"
  become: yes
  become_method: "su"
  become_user: "{{ user }}"
  become_flags: '-s /bin/sh'
  args:
    chdir: "{{ agentDir }}"

#- name: "Force TAR extraction on the Agent file"
#  command: "tar -zxvf /home/{{ user }}/myAgent/vsts-agent-linux-x64-2.160.0.tar.gz /home/{{ user }}/myAgent"
#  become: yes

...
